<?php

namespace Database\Seeders;

use App\Models\Cities;
use Illuminate\Database\Seeder;

class CitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */


    //seeds for cities
    public function run()
    {
        $cities = [
            ['name' => 'Port Blair' , 'state_id' => '1'],
            ['name' => 'Adoni' , 'state_id' => '2'],
            ['name' => 'Amaravati' , 'state_id' => '2'],
            ['name' => 'Anantapur' , 'state_id' => '2'],
            ['name' => 'Chandragiri' , 'state_id' => '2'],
            ['name' => 'Chittoor' , 'state_id' => '2'],
            ['name' => 'Dowlaiswaram' , 'state_id' => '2'],
            ['name' => 'Eluru' , 'state_id' => '2'],
            ['name' => 'Guntur' , 'state_id' => '2'],
            ['name' => 'Kadapa' , 'state_id' => '2'],
            ['name' => 'Kakinada' , 'state_id' => '2'],
            ['name' => 'Kurnool' , 'state_id' => '2'],
            ['name' => 'Machilipatnam' , 'state_id' => '2'],
            ['name' => 'Nagarjunakoṇḍa' , 'state_id' => '2'],
            ['name' => 'Rajahmundry' , 'state_id' => '2'],
            ['name' => 'Srikakulam' , 'state_id' => '2'],
            ['name' => 'Tirupati' , 'state_id' => '2'],
            ['name' => 'Vijayawada' , 'state_id' => '2'],
            ['name' => 'Visakhapatnam' , 'state_id' => '2'],
            ['name' => 'Vizianagaram' , 'state_id' => '2'],
            ['name' => 'Yemmiganur' , 'state_id' => '2'],
            ['name' => 'Itanagar' , 'state_id' => '3'],
            ['name' => 'Dhuburi' , 'state_id' => '4'],
            ['name' => 'Dibrugarh' , 'state_id' => '4'],
            ['name' => 'Dispur' , 'state_id' => '4'],
            ['name' => 'Guwahati' , 'state_id' => '4'],
            ['name' => 'Jorhat' , 'state_id' => '4'],
            ['name' => 'Nagaon' , 'state_id' => '4'],
            ['name' => 'Sibsagar' , 'state_id' => '4'],
            ['name' => 'Silchar' , 'state_id' => '4'],
            ['name' => 'Tezpur' , 'state_id' => '4'],
            ['name' => 'Tinsukia' , 'state_id' => '4'],
            ['name' => 'Ara', 'state_id' => '5'],
            ['name' => 'Baruni' , 'state_id' => '5'],
            ['name' => 'Begusarai' , 'state_id' => '5'],
            ['name' => 'Bettiah' , 'state_id' => '5'],
            ['name' => 'Bhagalpur' , 'state_id' => '5'],
            ['name' => 'Bhagalpur', 'state_id' => '5'],
            ['name' => 'Bihar Sharif', 'state_id' => '5'],
            ['name' => 'Bodh Gaya', 'state_id' => '5'],
            ['name' => 'Buxar', 'state_id' => '5'],
            ['name' => 'Chapra', 'state_id' => '5'],
            ['name' => 'Darbhanga', 'state_id' => '5'],
            ['name' => 'Dehri', 'state_id' => '5'],
            ['name' => 'Dinapur Nizamat', 'state_id' => '5'],
            ['name' => 'Gaya', 'state_id' => '5'],
            ['name' => 'Hajipur', 'state_id' => '5'],
            ['name' => 'Jamalpur', 'state_id' => '5'],
            ['name' => 'Katihar', 'state_id' => '5'],
            ['name' => 'Madhubani', 'state_id' => '5'],
            ['name' => 'Motihari', 'state_id' => '5'],
            ['name' => 'Munger', 'state_id' => '5'],
            ['name' => 'Muzaffarpur', 'state_id' => '5'],
            ['name' => 'Patna', 'state_id' => '5'],
            ['name' => 'Purnia', 'state_id' => '5'],
            ['name' => 'Pusa', 'state_id' => '5'],
            ['name' => 'Saharsa', 'state_id' => '5'],
            ['name' => 'Samastipur', 'state_id' => '5'],
            ['name' => 'Sasaram', 'state_id' => '5'],
            ['name' => 'Sitamarhi', 'state_id' => '5'],
            ['name' => 'Siwan', 'state_id' => '5'],
            ['name' => 'Ambikapur' , 'state_id' => '6'],
            ['name' => 'Bhilai' , 'state_id' => '6'],
            ['name' => 'Bilaspur' , 'state_id' => '6'],
            ['name' => 'Dhamtari' , 'state_id' => '6'],
            ['name' => 'Durg' , 'state_id' => '6'],
            ['name' => 'Jagdalpur' , 'state_id' => '6'],
            ['name' => 'Raipur' , 'state_id' => '6'],
            ['name' => 'Rajnandgaon' , 'state_id' => '6'],
            ['name' => 'Chandigarh' , 'state_id' => '7'],
            ['name' => 'Daman' , 'state_id' => '8'],
            ['name' => 'diu' , 'state_id' => '8'],
            ['name' => 'Delhi' , 'state_id' => '9'],
            ['name' => 'New Delhi' , 'state_id' => '9'],
            ['name' => 'Silvassa' , 'state_id' => '10'],
            ['name' => 'Madgaon' , 'state_id' => '11'],
            ['name' => 'Panaji' , 'state_id' => '11'],
            ['name' => 'Ahmadabad' , 'state_id' => '12'],
            ['name' => 'Amreli' , 'state_id' => '12'],
            ['name' => 'Bharuch' , 'state_id' => '12'],
            ['name' => 'Bhavnagar' , 'state_id' => '12'],
            ['name' => 'Bhuj' , 'state_id' => '12'],
            ['name' => 'Dwarka' , 'state_id' => '12'],
            ['name' => 'Gandhinagar' , 'state_id' => '12'],
            ['name' => 'Godhra' , 'state_id' => '12'],
            ['name' => 'Jamnagar' , 'state_id' => '12'],
            ['name' => 'Junagadh' , 'state_id' => '12'],
            ['name' => 'Kandla' , 'state_id' => '12'],
            ['name' => 'Khambhat' , 'state_id' => '12'],
            ['name' => 'Kheda' , 'state_id' => '12'],
            ['name' => 'Mahesana' , 'state_id' => '12'],
            ['name' => 'Morvi' , 'state_id' => '12'],
            ['name' => 'Nadiad' , 'state_id' => '12'],
            ['name' => 'Navsari' , 'state_id' => '12'],
            ['name' => 'Okha' , 'state_id' => '12'],
            ['name' => 'Palanpur' , 'state_id' => '12'],
            ['name' => 'Patan' , 'state_id' => '12'],
            ['name' => 'Porbandar' , 'state_id' => '12'],
            ['name' => 'Rajkot' , 'state_id' => '12'],
            ['name' => 'Surat' , 'state_id' => '12'],
            ['name' => 'Surendranagar' , 'state_id' => '12'],
            ['name' => 'Valsad' , 'state_id' => '12'],
            ['name' => 'Veraval' , 'state_id' => '12'],
            ['name' => 'Bilaspur' , 'state_id' => '13'],
            ['name' => 'Chamba' , 'state_id' => '13'],
            ['name' => 'Dalhousie' , 'state_id' => '13'],
            ['name' => 'Dharmshala' , 'state_id' => '13'],
            ['name' => 'Hamirpur' , 'state_id' => '13'],
            ['name' => 'Kangra' , 'state_id' => '13'],
            ['name' => 'Kullu' , 'state_id' => '13'],
            ['name' => 'Mandi' , 'state_id' => '13'],
            ['name' => 'Nahan' , 'state_id' => '13'],
            ['name' => 'Shimla' , 'state_id' => '13'],
            ['name' => 'Una' , 'state_id' => '13'],
            ['name' => 'Ambala' , 'state_id' => '14'],
            ['name' => 'Bhiwani' , 'state_id' => '14'],
            ['name' => 'Chandigarh' , 'state_id' => '14'],
            ['name' => 'Faridabad' , 'state_id' => '14'],
            ['name' => 'Firozpur Jhirka' , 'state_id' => '14'],
            ['name' => 'Gurgaon' , 'state_id' => '14'],
            ['name' => 'Hansi' , 'state_id' => '14'],
            ['name' => 'Hisar' , 'state_id' => '14'],
            ['name' => 'Jind' , 'state_id' => '14'],
            ['name' => 'Kaithal' , 'state_id' => '14'],
            ['name' => 'Karnal' , 'state_id' => '14'],
            ['name' => 'Kurukshetra','state_id' => '14'],
            ['name' => 'Panipat' , 'state_id' =>'14'],
            ['name' => 'Pehowa' , 'state_id' => '14'],
            ['name' => 'Rewari' , 'state_id' => '14'],
            ['name' => 'Rohtak' , 'state_id' => '14'],
            ['name' => 'Sirsa' , 'state_id' => '14'],
            ['name' => 'Sonipat' , 'state_id' => '14'],
            ['name' => 'Anantnag' , 'state_id' => '15'],
            ['name' => 'Baramula' , 'state_id' => '15'],
            ['name' => 'Doda' , 'state_id' => '15'],
            ['name' => 'Gulmarg' , 'state_id' => '15'],
            ['name' => 'Jammu' , 'state_id' => '15'],
            ['name' => 'Kathua' , 'state_id' => '15'],
            ['name' => 'Punch' , 'state_id' => '15'],
            ['name' => 'Rajauri' , 'state_id' => '15'],
            ['name' => 'Srinagar' , 'state_id' => '15'],
            ['name' => 'Udhampur' , 'state_id' => '15'],
            ['name' => 'Bokaro' , 'state_id' => '16'],
            ['name' => 'Chaibasa' , 'state_id' => '16'],
            ['name' => 'Deoghar' , 'state_id' => '16'],
            ['name' => 'Dhanbad' , 'state_id' => '16'],
            ['name' => 'Dumka' , 'state_id' => '16'],
            ['name' => 'Giridih' , 'state_id' => '16'],
            ['name' => 'Hazaribag' , 'state_id' => '16'],
            ['name' => 'Jamshedpur' , 'state_id' => '16'],
            ['name' => 'Jharia' , 'state_id' => '16'],
            ['name' => 'Rajmahal' , 'state_id' => '16'],
            ['name' => 'Ranchi' , 'state_id' => '16'],
            ['name' => 'Saraikela' , 'state_id' => '16'],
            ['name' => 'Alappuzha' , 'state_id' => '17'],
            ['name' => 'Badagara' , 'state_id' => '17'],
            ['name' => 'Idukki' , 'state_id' => '17'],
            ['name' => 'Kannur' , 'state_id' => '17'],
            ['name' => 'Kochi' , 'state_id' => '17'],
            ['name' => 'Kollam' , 'state_id' => '17'],
            ['name' => 'Kottayam' , 'state_id' => '17'],
            ['name' => 'Kozhikode' , 'state_id' => '17'],
            ['name' => 'Mattancheri' , 'state_id' => '17'],
            ['name' => 'Palakkad' , 'state_id' => '17'],
            ['name' => 'Thalassery' , 'state_id' => '17'],
            ['name' => 'Thiruvananthapuram' , 'state_id' => '17'],
            ['name' => 'Thrissur' , 'state_id' => '17'], 
            ['name' => 'Badami' , 'state_id' => '18'],
            ['name' => 'Ballari' , 'state_id' => '18'],
            ['name' => 'Bangalore' , 'state_id' => '18'],
            ['name' => 'Belgavi' , 'state_id' => '18'],
            ['name' => 'Bhadravati' , 'state_id' => '18'],
            ['name' => 'Bidar' , 'state_id' => '18'],
            ['name' => 'Chikkamagaluru' , 'state_id' => '18'],
            ['name' => 'Chitradurga' , 'state_id' => '18'],
            ['name' => 'Davangere' , 'state_id' => '18'],
            ['name' => 'Halebid' , 'state_id' => '18'],
            ['name' => 'Hassan' , 'state_id' => '18'],
            ['name' => 'Hubballi-Dharwad' , 'state_id' => '18'],
            ['name' => 'Kalaburagi' , 'state_id' => '18'],
            ['name' => 'Kolar' , 'state_id' => '18'],
            ['name' => 'Madikeri' , 'state_id' => '18'],
            ['name' => 'Mandya' , 'state_id' => '18'],
            ['name' => 'Mangaluru' , 'state_id' => '18'],
            ['name' => 'Mysuru' , 'state_id' => '18'],
            ['name' => 'Raichur' , 'state_id' => '18'],
            ['name' => 'Shivamogga' , 'state_id' => '18'],
            ['name' => 'Shravanabelagola' , 'state_id' => '18'],
            ['name' => 'Shrirangapattana' , 'state_id' => '18'],
            ['name' => 'Tumkuru' , 'state_id' => '18'],
            ['name' => 'Lakshadweep' , 'state_id' => '19'],
            ['name' => 'Cherrapunji' , 'state_id' => '20'],
            ['name' => 'Shillong' , 'state_id' => '20'],
            ['name' => 'Ahmadnagar' , 'state_id' => '21'],
            ['name' => 'Akola' , 'state_id' => '21'],
            ['name' => 'Amravati' , 'state_id' => '21'],
            ['name' => 'Aurangabad' , 'state_id' => '21'],
            ['name' => 'Bhandara' , 'state_id' => '21'],
            ['name' => 'Bhusawal' , 'state_id' => '21'],
            ['name' => 'Bid' , 'state_id' => '21'],
            ['name' => 'Buldana' , 'state_id' => '21'],
            ['name' => 'Chandrapur' , 'state_id' => '21'],
            ['name' => 'Daulatabad' , 'state_id' => '21'],
            ['name' => 'Dhule' , 'state_id' => '21'],
            ['name' => 'Jalgaon' , 'state_id' => '21'],
            ['name' => 'Kalyan' , 'state_id' => '21'],
            ['name' => 'Karli' , 'state_id' => '21'],
            ['name' => 'Kolhapur' , 'state_id' => '21'],
            ['name' => 'Mahabaleshwar' , 'state_id' => '21'],
            ['name' => 'Malegaon' , 'state_id' => '21'],
            ['name' => 'Matheran' , 'state_id' => '21'],
            ['name' => 'Mumbai' , 'state_id' => '21'],
            ['name' => 'Nagpur' , 'state_id' => '21'],
            ['name' => 'Nanded' , 'state_id' => '21'],
            ['name' => 'Nashik' , 'state_id' => '21'],
            ['name' => 'Osmanabad' , 'state_id' => '21'],
            ['name' => 'Pandharpur' , 'state_id' => '21'],
            ['name' => 'Parbhani' , 'state_id' => '21'],
            ['name' => 'Pune' , 'state_id' => '21'],
            ['name' => 'Ratnagiri' , 'state_id' => '21'],
            ['name' => 'Sangli' , 'state_id' => '21'],
            ['name' => 'Satara' , 'state_id' => '21'],
            ['name' => 'Sevagram' , 'state_id' => '21'],
            ['name' => 'Solapur' , 'state_id' => '21'],
            ['name' => 'Thane' , 'state_id' => '21'],
            ['name' => 'Ulhasnagar' , 'state_id' => '21'],
            ['name' => 'Vasai-Virar' , 'state_id' => '21'],
            ['name' => 'Wardha' , 'state_id' => '21'],
            ['name' => 'Yavatmal' , 'state_id' => '21'],
            ['name' => 'Impahal' , 'state_id' => '22'],
            ['name' => 'Balaghat' , 'state_id' => '23'],
            ['name' => 'Barwani' , 'state_id' => '23'],
            ['name' => 'Betul' , 'state_id' => '23'],
            ['name' => 'Bharhut' , 'state_id' => '23'],
            ['name' => 'Bhind' , 'state_id' => '23'],
            ['name' => 'Bhojpur' , 'state_id' => '23'],
            ['name' => 'Bhopal' , 'state_id' => '23'],
            ['name' => 'Burhanpur' , 'state_id' => '23'],
            ['name' => 'Chhatarpur' , 'state_id' => '23'],
            ['name' => 'Chhindwara' , 'state_id' => '23'],
            ['name' => 'Damoh' , 'state_id' => '23'],
            ['name' => 'Datia' , 'state_id' => '23'],
            ['name' => 'Dewas' , 'state_id' => '23'],
            ['name' => 'Dhar' , 'state_id' => '23'],
            ['name' => 'Guna' , 'state_id' => '23'],
            ['name' => 'Gwalior' , 'state_id' => '23'],
            ['name' => 'Hoshangabad' , 'state_id' => '23'],
            ['name' => 'Indore' , 'state_id' => '23'],
            ['name' => 'Itarsi' , 'state_id' => '23'],
            ['name' => 'Jabalpur' , 'state_id' => '23'],
            ['name' => 'Jhabua' , 'state_id' => '23'],
            ['name' => 'Khajuraho' , 'state_id' => '23'],
            ['name' => 'Khandwa' , 'state_id' => '23'],
            ['name' => 'Khargon' , 'state_id' => '23'],
            ['name' => 'Maheshwar' , 'state_id' => '23'],
            ['name' => 'Mandla' , 'state_id' => '23'],
            ['name' => 'Mandsaur' , 'state_id' => '23'],
            ['name' => 'Mhow' , 'state_id' => '23'],
            ['name' => 'Morena' , 'state_id' => '23'],
            ['name' => 'Murwara' , 'state_id' => '23'],
            ['name' => 'Narsimhapur' , 'state_id' => '23'],
            ['name' => 'Narsinghgarh' , 'state_id' => '23'],
            ['name' => 'Narwar' , 'state_id' => '23'],
            ['name' => 'Neemuch' , 'state_id' => '23'],
            ['name' => 'Nowgong' , 'state_id' => '23'],
            ['name' => 'Orchha' , 'state_id' => '23'],
            ['name' => 'Panna' , 'state_id' => '23'],
            ['name' => 'Raisen' , 'state_id' => '23'],
            ['name' => 'Rajgarh' , 'state_id' => '23'],
            ['name' => 'Ratlam' , 'state_id' => '23'],
            ['name' => 'Rewa' , 'state_id' => '23'],
            ['name' => 'Sagar' , 'state_id' => '23'],
            ['name' => 'Sarangpur' , 'state_id' => '23'],
            ['name' => 'Satna' , 'state_id' => '23'],
            ['name' => 'Sehore' , 'state_id' => '23'],
            ['name' => 'Seoni' , 'state_id' => '23'],
            ['name' => 'Shahdol' , 'state_id' => '23'],
            ['name' => 'Shajapur' , 'state_id' => '23'],
            ['name' => 'Sheopur' , 'state_id' => '23'],
            ['name' => 'Shivpuri' , 'state_id' => '23'],
            ['name' => 'Ujjain' , 'state_id' => '23'],
            ['name' => 'Vidisha' , 'state_id' => '23'],
            ['name' => 'Aizawl' , 'state_id' => '24'],
            ['name' => 'Lunglei' , 'state_id' => '24'],
            ['name' => 'Kohima' , 'state_id' => '25'],
            ['name' => 'Mon' , 'state_id' => '25'],
            ['name' => 'Phek' , 'state_id' => '25'],
            ['name' => 'Wokha' , 'state_id' => '25'],
            ['name' => 'Zunheboto' , 'state_id' => '25'],
            ['name' => 'Balangir' , 'state_id' => '26'],
            ['name' => 'Baleshwar' , 'state_id' => '26'],
            ['name' => 'Baripada' , 'state_id' => '26'],
            ['name' => 'Bhubaneshwar' , 'state_id' => '26'],
            ['name' => 'Brahmapur' , 'state_id' => '26'],
            ['name' => 'Cuttack' , 'state_id' => '26'],
            ['name' => 'Dhenkanal' , 'state_id' => '26'],
            ['name' => 'Keonjhar' , 'state_id' => '26'],
            ['name' => 'Konark' , 'state_id' => '26'],
            ['name' => 'Koraput' , 'state_id' => '26'],
            ['name' => 'Paradip' , 'state_id' => '26'],
            ['name' => 'Phulabani' , 'state_id' => '26'],
            ['name' => 'Puri' , 'state_id' => '26'],
            ['name' => 'Sambalpur' , 'state_id' => '26'],
            ['name' => 'Udayagiri' , 'state_id' => '26'],
            ['name' => 'Amritsar' , 'state_id' => '27'],
            ['name' => 'Batala' , 'state_id' => '27'],
            ['name' => 'Chandigarh' , 'state_id' => '27'],
            ['name' => 'Faridkot' , 'state_id' => '27'],
            ['name' => 'Firozpur' , 'state_id' => '27'],
            ['name' => 'Gurdaspur' , 'state_id' => '27'],
            ['name' => 'Hoshiarpur' , 'state_id' => '27'],
            ['name' => 'Jalandhar' , 'state_id' => '27'],
            ['name' => 'Kapurthala' , 'state_id' => '27'],
            ['name' => 'Ludhiana' , 'state_id' => '27'],
            ['name' => 'Nabha' , 'state_id' => '27'],
            ['name' => 'Patiala' , 'state_id' => '27'],
            ['name' => 'Rupnagar' , 'state_id' => '27'],
            ['name' => 'Sangrur' , 'state_id' => '27'],
            ['name' => 'Karaikal' , 'state_id' => '28'],
            ['name' => 'Mahe' , 'state_id' => '28'],
            ['name' => 'Puducherry' , 'state_id' => '28'],
            ['name' => 'Yanam' , 'state_id' => '28'],
            ['name' => 'Abu' , 'state_id' => '29'],
            ['name' => 'Ajmer' , 'state_id' => '29'],
            ['name' => 'Alwar' , 'state_id' => '29'],
            ['name' => 'Amer' , 'state_id' => '29'],
            ['name' => 'Barmer' , 'state_id' => '29'],
            ['name' => 'Beawar' , 'state_id' => '29'],
            ['name' => 'Bharatpur' , 'state_id' => '29'],
            ['name' => 'Bhilwara' , 'state_id' => '29'],
            ['name' => 'Bikaner' , 'state_id' => '29'],
            ['name' => 'Bundi' , 'state_id' => '29'],
            ['name' => 'Chittaurgarh' , 'state_id' => '29'],
            ['name' => 'Churu' , 'state_id' => '29'],
            ['name' => 'Dhaulpur' , 'state_id' => '29'],
            ['name' => 'Dungarpur' , 'state_id' => '29'],
            ['name' => 'Ganganagar' , 'state_id' => '29'],
            ['name' => 'Hanumangarh' , 'state_id' => '29'],
            ['name' => 'Jaipur' , 'state_id' => '29'],
            ['name' => 'Jaisalmer' , 'state_id' => '29'],
            ['name' => 'Jalor' , 'state_id' => '29'],
            ['name' => 'Jhalawar' , 'state_id' => '29'],
            ['name' => 'Jhunjhunu' , 'state_id' => '29'],
            ['name' => 'Jodhpur' , 'state_id' => '29'],
            ['name' => 'Kishangarh' , 'state_id' => '29'],
            ['name' => 'Kota' , 'state_id' => '29'],
            ['name' => 'Merta' , 'state_id' => '29'],
            ['name' => 'Nagaur' , 'state_id' => '29'],
            ['name' => 'Nathdwara' , 'state_id' => '29'],
            ['name' => 'Pali' , 'state_id' => '29'],
            ['name' => 'Phalodi' , 'state_id' => '29'],
            ['name' => 'Pushkar' , 'state_id' => '29'],
            ['name' => 'Sawai Madhopur' , 'state_id' => '29'],
            ['name' => 'Shahpura' , 'state_id' => '29'],
            ['name' => 'Sikar' , 'state_id' => '29'],
            ['name' => 'Sirohi' , 'state_id' => '29'],
            ['name' => 'Tonk' , 'state_id' => '29'],
            ['name' => 'Udaipur' , 'state_id' => '29'],
            ['name' => 'Gangtok' , 'state_id' => '30'],
            ['name' => 'Gyalsing' , 'state_id' => '30'],
            ['name' => 'Lachung' , 'state_id' => '30'],
            ['name' => 'Mangan' , 'state_id' => '30'],
            ['name' => 'Arcot' , 'state_id' => '31'],
            ['name' => 'Chengalpattu' , 'state_id' => '31'],
            ['name' => 'Chennai' , 'state_id' => '31'],
            ['name' => 'Chidambaram' , 'state_id' => '31'],
            ['name' => 'Coimbatore' , 'state_id' => '31'],
            ['name' => 'Cuddalore' , 'state_id' => '31'],
            ['name' => 'Dharmapuri' , 'state_id' => '31'],
            ['name' => 'Dindigul' , 'state_id' => '31'],
            ['name' => 'Erode' , 'state_id' => '31'],
            ['name' => 'Kanchipuram' , 'state_id' => '31'],
            ['name' => 'Kanniyakumari' , 'state_id' => '31'],
            ['name' => 'Kodaikanal' , 'state_id' => '31'],
            ['name' => 'Kumbakonam' , 'state_id' => '31'],
            ['name' => 'Madurai' , 'state_id' => '31'],
            ['name' => 'Mamallapuram' , 'state_id' => '31'],
            ['name' => 'Nagappattinam' , 'state_id' => '31'],
            ['name' => 'Nagercoil' , 'state_id' => '31'],
            ['name' => 'Palayankottai' , 'state_id' => '31'],
            ['name' => 'Pudukkottai' , 'state_id' => '31'],
            ['name' => 'Rajapalaiyam' , 'state_id' => '31'],
            ['name' => 'Ramanathapuram' , 'state_id' => '31'],
            ['name' => 'Salem' , 'state_id' => '31'],
            ['name' => 'Thanjavur' , 'state_id' => '31'],
            ['name' => 'Tiruchchirappalli' , 'state_id' => '31'],
            ['name' => 'Tirunelveli' , 'state_id' => '31'],
            ['name' => 'Tiruppur' , 'state_id' => '31'],
            ['name' => 'Tuticorin' , 'state_id' => '31'],
            ['name' => 'Udhagamandalam' , 'state_id' => '31'],
            ['name' => 'Vellore' , 'state_id' => '31'],
            ['name' => 'Agartala' , 'state_id' => '32'],
            ['name' => 'Almora' , 'state_id' => '33'],
            ['name' => 'Dehra Dun' , 'state_id' => '33'],
            ['name' => 'Haridwar' , 'state_id' => '33'],
            ['name' => 'Mussoorie' , 'state_id' => '33'],
            ['name' => 'Nainital' , 'state_id' => '33'],
            ['name' => 'Pithoragarh' , 'state_id' => '33'],
            ['name' => 'Agra' , 'state_id' => '34'],
            ['name' => 'Aligarh' , 'state_id' => '34'],
            ['name' => 'Amroha' , 'state_id' => '34'],
            ['name' => 'Ayodhya' , 'state_id' => '34'],
            ['name' => 'Azamgarh' , 'state_id' => '34'],
            ['name' => 'Bahraich' , 'state_id' => '34'],
            ['name' => 'Ballia' , 'state_id' => '34'],
            ['name' => 'Banda' , 'state_id' => '34'],
            ['name' => 'Bara Banki' , 'state_id' => '34'],
            ['name' => 'Bareilly' , 'state_id' => '34'],
            ['name' => 'Basti' , 'state_id' => '34'],
            ['name' => 'Bijnor' , 'state_id' => '34'],
            ['name' => 'Bithur' , 'state_id' => '34'],
            ['name' => 'Budaun' , 'state_id' => '34'],
            ['name' => 'Bulandshahr' , 'state_id' => '34'],
            ['name' => 'Deoria' , 'state_id' => '34'],
            ['name' => 'Etah' , 'state_id' => '34'],
            ['name' => 'Etawah' , 'state_id' => '34'],
            ['name' => 'Faizabad' , 'state_id' => '34'],
            ['name' => 'Farrukhabad-cum-Fatehgarh' , 'state_id' => '34'],
            ['name' => 'Fatehpur' , 'state_id' => '34'],
            ['name' => 'Fatehpur Sikri' , 'state_id' => '34'],
            ['name' => 'Ghaziabad' , 'state_id' => '34'],
            ['name' => 'Ghazipur' , 'state_id' => '34'],
            ['name' => 'Gonda' , 'state_id' => '34'],
            ['name' => 'Gorakhpur' , 'state_id' => '34'],
            ['name' => 'Hamirpur' , 'state_id' => '34'],
            ['name' => 'Hardoi' , 'state_id' => '34'],
            ['name' => 'Hathras' , 'state_id' => '34'],
            ['name' => 'Jalaun' , 'state_id' => '34'],
            ['name' => 'Jaunpur' , 'state_id' => '34'],
            ['name' => 'Jhansi' , 'state_id' => '34'],
            ['name' => 'Kannauj' , 'state_id' => '34'],
            ['name' => 'Kanpur' , 'state_id' => '34'],
            ['name' => 'Lakhimpur' , 'state_id' => '34'],
            ['name' => 'Lalitpur' , 'state_id' => '34'],
            ['name' => 'Lucknow' , 'state_id' => '34'],
            ['name' => 'Mainpuri' , 'state_id' => '34'],
            ['name' => 'Mathura' , 'state_id' => '34'],
            ['name' => 'Meerut' , 'state_id' => '34'],
            ['name' => 'Mirzapur-Vindhyachal' , 'state_id' => '34'],
            ['name' => 'Moradabad' , 'state_id' => '34'],
            ['name' => 'Muzaffarnagar' , 'state_id' => '34'],
            ['name' => 'Partapgarh' , 'state_id' => '34'],
            ['name' => 'Pilibhit' , 'state_id' => '34'],
            ['name' => 'Prayagraj' , 'state_id' => '34'],
            ['name' => 'Rae Bareli' , 'state_id' => '34'],
            ['name' => 'Rampur' , 'state_id' => '34'],
            ['name' => 'Saharanpur' , 'state_id' => '34'],
            ['name' => 'Sambhal' , 'state_id' => '34'],
            ['name' => 'Shahjahanpur' , 'state_id' => '34'],
            ['name' => 'Sitapur' , 'state_id' => '34'],
            ['name' => 'Sultanpur' , 'state_id' => '34'],
            ['name' => 'Tehri' , 'state_id' => '34'],
            ['name' => 'Varanasi' , 'state_id' => '34'],
            ['name' => 'Alipore' , 'state_id' => '35'],
            ['name' => 'Alipur Duar' , 'state_id' => '35'],
            ['name' => 'Asansol' , 'state_id' => '35'],
            ['name' => 'Baharampur' , 'state_id' => '35'],
            ['name' => 'Bally' , 'state_id' => '35'],
            ['name' => 'Balurghat' , 'state_id' => '35'],
            ['name' => 'Bankura' , 'state_id' => '35'],
            ['name' => 'Baranagar' , 'state_id' => '35'],
            ['name' => 'Barasat' , 'state_id' => '35'],
            ['name' => 'Barrackpore' , 'state_id' => '35'],
            ['name' => 'Basirhat' , 'state_id' => '35'],
            ['name' => 'Bhatpara' , 'state_id' => '35'],
            ['name' => 'Bishnupur' , 'state_id' => '35'],
            ['name' => 'Budge Budge' , 'state_id' => '35'],
            ['name' => 'Burdwan' , 'state_id' => '35'],
            ['name' => 'Chandernagore' , 'state_id' => '35'],
            ['name' => 'Darjiling' , 'state_id' => '35'],
            ['name' => 'Diamond Harbour' , 'state_id' => '35'],
            ['name' => 'Dum Dum' , 'state_id' => '35'],
            ['name' => 'Durgapur' , 'state_id' => '35'],
            ['name' => 'Halisahar' , 'state_id' => '35'],
            ['name' => 'Haora' , 'state_id' => '35'],
            ['name' => 'Hugli' , 'state_id' => '35'],
            ['name' => 'Ingraj Bazar' , 'state_id' => '35'],
            ['name' => 'Jalpaiguri' , 'state_id' => '35'],
            ['name' => 'Kalimpong' , 'state_id' => '35'],
            ['name' => 'Kamarhati' , 'state_id' => '35'],
            ['name' => 'Kanchrapara' , 'state_id' => '35'],
            ['name' => 'Kharagpur' , 'state_id' => '35'],
            ['name' => 'Koch Bihar' , 'state_id' => '35'],
            ['name' => 'Kolkata' , 'state_id' => '35'],
            ['name' => 'Krishnanagar' , 'state_id' => '35'],
            ['name' => 'Malda' , 'state_id' => '35'],
            ['name' => 'Midnapore' , 'state_id' => '35'],
            ['name' => 'Murshidabad' , 'state_id' => '35'],
            ['name' => 'Navadwip' , 'state_id' => '35'],
            ['name' => 'Palashi' , 'state_id' => '35'],
            ['name' => 'Panihati' , 'state_id' => '35'],
            ['name' => 'Purulia' , 'state_id' => '35'],
            ['name' => 'Raiganj' , 'state_id' => '35'],
            ['name' => 'Santipur' , 'state_id' => '35'],
            ['name' => 'Shantiniketan' , 'state_id' => '35'],
            ['name' => 'Shrirampur' , 'state_id' => '35'],
            ['name' => 'Siliguri' , 'state_id' => '35'],
            ['name' => 'Siuri' , 'state_id' => '35'],
            ['name' => 'Tamluk' , 'state_id' => '35'],
            ['name' => 'Titagarh' , 'state_id' => '35'],
            ['name' => 'Hyderabad' , 'state_id' => '36'],
            ['name' => 'Karimnagar' , 'state_id' => '36'],
            ['name' => 'Khammam' , 'state_id' => '36'],
            ['name' => 'Mahbubnagar' , 'state_id' => '36'],
            ['name' => 'Nizamabad' , 'state_id' => '36'],
            ['name' => 'Sangareddi' , 'state_id' => '36'],
            ['name' => 'Warangal' , 'state_id' => '36'],
            ['name' => 'Tripura' , 'state_id' => '36']
            
        ];

        Cities::insert($cities);
    }
}
